env:
  nodeEnv: dev
api:
  port: 3000
  host: localhost
database:
  connectionHost: localhost
  connectionPort: 5432
  connectionUser: acme
  connectionPassword: acme@123
  ormMaxPoolSize: 40
  ormIdleTimeoutMillis: 10000
  ormAutoSync: false
  dbNameUser: db_user