env:
  nodeEnv: dev
api:
  port: 3000
  host: localhost
database:
  connection:
    host: localhost
    port: 5432
    username: acme
    password: acme@123
  orm:
    maxPoolSize: 40
    idleTimeoutMillis: 10000
    autoSync: false
  user: db_user