services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme@123
      POSTGRES_DB: acme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acme"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: db